name: Trigger Account B Deploy
on:
  push:
    branches:
      - main

jobs:
  trigger-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Call Account B Deploy Hook
        # Added '-f' to fail if the link is broken
        # Added '-v' to show details in the logs
        run: |
          curl -f -v -X POST "https://api.vercel.com/v1/integrations/deploy/prj_qtmfmiMwBxLwOiG3BLFeUxFGM3Ly/wxcnxvfV1Z"
