name: Trigger Account B Deploy
on:
  push:
    branches:
      - main  # same branch Account A uses

jobs:
  trigger-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Call Account B Deploy Hook
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_qtmfmiMwBxLwOiG3BLFeUxFGM3Ly/cvwsEbcenH"
